defaults: &defaults
  interval: "1m"
  sites:
    - "http://google.com"
  http_timeout: 15

development:
  <<: *defaults
  database_url: "sqlite3:///development.sqlite3"

test:
  <<: *defaults
  database_url: "sqlite3:///test.sqlite3"

production:
  <<: *defaults
  database_url: <%= ENV["DATABASE_URL"] %>
  sites: <%= ENV["CHECK_URLS"].split(",") %>