defaults: &defaults
  interval: "1m"
  sites:
    - "http://google.com"
    - "http://yahoo.com"
  http:
    concurrency: 20
    timeout: 15

development:
  <<: *defaults
  database_url: "sqlite3:///development.sqlite3"

test:
  <<: *defaults
  database_url: "sqlite3:///test.sqlite3"

production:
  <<: *defaults
  database_url: <%= ENV["DATABASE_URL"] %>
  sites: <%= ENV["CHECK_URLS"].split(",") rescue [""] %>
  interval: <%= ENV["CHECK_INTERVAL"] || "1m" %>
  http:
    concurrency: <%= ENV["HTTP_CONCURRENCY"] ? ENV["HTTP_CONCURRENCY"].to_i : 5 %>
    timeout: <%= ENV["HTTP_TIMEOUT"] ? ENV["HTTP_TIMEOUT"].to_i : 15 %>
