defaults: &defaults
  interval: "1m"
  sites:
    - "http://google.com"
    - "http://yahoo.com"
  http:
    concurrency: 20
    timeout: 15
  email:
    sender: picket@email.com
    receiver: receiver@email.com

development:
  <<: *defaults
  database_url: "sqlite3:///development.sqlite3"

test:
  <<: *defaults
  database_url: "sqlite3::memory:"

production:
  <<: *defaults
  database_url: <%= ENV["DATABASE_URL"] %>
  sites: <%= ENV["CHECK_URLS"].split(",") rescue [""] %>
  interval: <%= ENV["CHECK_INTERVAL"] || "1m" %>
  http:
    concurrency: <%= ENV["HTTP_CONCURRENCY"] ? ENV["HTTP_CONCURRENCY"].to_i : 2 %>
    timeout: <%= ENV["HTTP_TIMEOUT"] ? ENV["HTTP_TIMEOUT"].to_i : 15 %>
  email:
    sender: <%= ENV["EMAIL_SENDER"] %>
    receiver: <%= ENV["EMAIL_RECEIVER"] %>
    username: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    domain: <%= ENV['SENDGRID_DOMAIN'] %>
